---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

Welcome to my website where I document my analysis used in my project. 

Initial code from the project can be found [here](https://github.com/ashleymulford/ACCOuNT/tree/master/scripts).

Specifically, this will look at the analysis of creatinine clearance. Creatinine is a waste product produced in our body. Low creatinine levels indicate kidney damage while high levels indicate diminished kidney function.

This analysis uses the Clopidogrel and NOAC drug groups.

These scripts document preparing the various files for the analysis.

1. [Extracting and Merging Phenotype Data](pheno.html)

2. [Calculating Creatinine Clearance](calculation_clop_CrCl.html)

3. [Finishing the Data Files](adjusting_data_files.html)

4. [Histogram of Phenotype Data](phenotype_data_analysis.html)

5. [Creating the Dosage Files](pred_dosages.html)

These scripts document the analysis for PWAS.

6. [Running PrediXcan](pwas.html)

7. [Covariates](covariates.html)

8. [GEMMA Association Studies](association_studies_gemma.html)

9. [Correct Bonferroni](correct_bonferroni.html)

10. [PWAS Plots](pwas_plots.html)

11. [PWAS Results](pwas_results.html)

These scripts document the analysis for GWAS.

12. [Dosage File to BIMBAM Format](dosage_to_bimbam.html)

13. [Running GEMMA for GWAS](gwas.html)

14. [GWAS Plots](gwas_plots.html)

These scripts document the analysis for TWAS.

15. [PrediXcan for TWAS](twas.html)

16. [TWAS Plots](twas_plots.html)


